CREATE DATABASE `dao_db`;
CREATE TABLE `dao_db`.`Users` (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Email VARCHAR(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LastLogin TIMESTAMP NULL,
    IsActive BOOLEAN DEFAULT FALSE
);
CREATE TABLE `dao_db`.`Membership` (
    MembershipID INT AUTO_INCREMENT PRIMARY KEY,
    UserID INT NOT NULL,
    ActivationToken VARCHAR(255) NOT NULL UNIQUE,
    TokenExpiry TIMESTAMP NOT NULL,
    IsActivated BOOLEAN DEFAULT FALSE,
    ActivatedAt TIMESTAMP NULL,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);
