CREATE TABLE `todo_db`.`Tasks` (`id` INT(11) NOT NULL AUTO_INCREMENT , `title` VARCHAR(255) NULL , `description` VARCHAR(2500) NULL , `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `Tasks` ADD `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NULL DEFAULT NULL AFTER `created_at`;
ALTER TABLE `Tasks` ADD `isComplete` BOOLEAN NULL AFTER `updated_at`;
