CREATE DATABASE `dtd_db` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
CREATE TABLE `dtd_db`.`Items` (`id` INT(11) NOT NULL AUTO_INCREMENT , `title` VARCHAR(255) NULL , `description` VARCHAR(2500) NULL , `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP , PRIMARY KEY (`id`)) ENGINE = InnoDB;
ALTER TABLE `Items` ADD `updated_at` TIMESTAMP on update CURRENT_TIMESTAMP NULL DEFAULT NULL AFTER `created_at`;
ALTER TABLE `Items` ADD `isComplete` BOOLEAN NULL AFTER `updated_at`;
